apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  selector:
    matchLabels:
      app: catalog-api
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: api
        image: adamkwolek.azurecr.io/catalogapi:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: catalog-api